In [2]:
import pickle
import numpy as np
import pandas as pd

In [85]:
%%bash
ls pkls/

X_train_test_y_train_test.pkl
X_y_ternary.pkl
cardiac_arrest_dfs.pkl
dem_hosp_dx_proc_orig_X_dfs.pkl
full_X_y_df.pkl
gbc_model.pkl
grid_gbc.pkl
logr_tree_forest_gridsearch.pkl
logr_tree_forest_svc_gridsearch.pkl
master_influenza_df.pkl
prediction_vector.pkl
scaled_X_train_test_y_train_test.pkl
svm_logr_tree_forest_mlp_gridsearch.pkl
y_h2o_full_df.pkl
y_h2o_test_df.pkl
y_h2o_test_df_2.pkl


In [234]:
with open("pkls/grid_gbc.pkl", "rb") as picklefile:
    grid_gbc=pickle.load(picklefile)

In [235]:
gbc_model = grid_gbc.best_estimator_

In [236]:
with open("pkls/gbc_model.pkl", "wb") as picklefile:
    pickle.dump(grid_gbc.best_estimator_, picklefile)

In [238]:
with open("pkls/scaled_X_train_test_y_train_test.pkl", "rb") as picklefile:
    [X_train, X_test, y_train, y_test] = pickle.load(picklefile)

In [239]:
X_train.head()

sex_code_F  sex_code_M  sex_code_U  race_1  race_2  race_3  \
record_id                                                                  
420110761749           0           1           0       0       0       1   
220110514002           1           0           0       0       0       1   
120110304733           0           1           0       0       0       0   
120110426880           0           1           0       0       0       0   
220110444681           0           0           0       0       0       1   

              race_4  race_5  race_`  ethnicity_1  ...   3761  9390  8872  \
record_id                                          ...                      
420110761749       0       0       0            0  ...      0     0     0   
220110514002       0       0       0            0  ...      0     0     0   
120110304733       1       0       0            1  ...      0     0     0   
120110426880       0       1       0            0  ...      0     0     0   
220110444681       0       0       0            0  ...      0     0     0   

              3607  0045  3324  4311  3404  3961  9915  
record_id                                               
420110761749     0     0     0     0     0     0     0  
220110514002     0     0     0     0     0     0     0  
120110304733     0     0     0     0     0     0     0  
120110426880     0     0     0     0     0     0     0  
220110444681     0     0     0     1     0     0     0  

[5 rows x 135 columns]

In [240]:
list(X_train.columns)

['sex_code_F',
 'sex_code_M',
 'sex_code_U',
 'race_1',
 'race_2',
 'race_3',
 'race_4',
 'race_5',
 'race_`',
 'ethnicity_1',
 'ethnicity_2',
 'ethnicity_`',
 'public_health_region_01',
 'public_health_region_02',
 'public_health_region_03',
 'public_health_region_04',
 'public_health_region_05',
 'public_health_region_06',
 'public_health_region_07',
 'public_health_region_08',
 'public_health_region_09',
 'public_health_region_10',
 'public_health_region_11',
 'first_payment_src_09',
 'first_payment_src_11',
 'first_payment_src_12',
 'first_payment_src_13',
 'first_payment_src_14',
 'first_payment_src_15',
 'first_payment_src_16',
 'first_payment_src_AM',
 'first_payment_src_BL',
 'first_payment_src_CH',
 'first_payment_src_CI',
 'first_payment_src_HM',
 'first_payment_src_LM',
 'first_payment_src_MA',
 'first_payment_src_MB',
 'first_payment_src_MC',
 'first_payment_src_OF',
 'first_payment_src_VA',
 'first_payment_src_WC',
 'first_payment_src_ZZ',
 'pat_age',
 'hiv_drug',
 'type_o

In [241]:
%%bash
ls pkls/

X_train_test_y_train_test.pkl
cardiac_arrest_dfs.pkl
dem_hosp_dx_proc_orig_X_dfs.pkl
gbc_model.pkl
grid_gbc.pkl
logr_tree_forest_gridsearch.pkl
logr_tree_forest_svc_gridsearch.pkl
scaled_X_train_test_y_train_test.pkl


In [12]:
with open("pkls/dem_hosp_dx_proc_orig_X_dfs.pkl", "rb") as picklefile:
    [X_demographic, X_hospital, X_diagnoses, X_procedures, X_orig] = pickle.load(picklefile)

In [13]:
X_demographic.head()

sex_code_F  sex_code_M  sex_code_U  race_1  race_2  race_3  \
record_id                                                                  
120110921391           0           1           0       0       0       0   
120110922505           1           0           0       0       0       1   
120110921645           1           0           0       0       0       0   
120110919484           1           0           0       0       0       0   
120110919499           0           1           0       0       0       0   

              race_4  race_5  race_`  ethnicity_1    ...     \
record_id                                            ...      
120110921391       1       0       0            0    ...      
120110922505       0       0       0            0    ...      
120110921645       1       0       0            0    ...      
120110919484       1       0       0            0    ...      
120110919499       0       1       0            1    ...      

              first_payment_src_LM  first_payment_src_MA  \
record_id                                                  
120110921391                     0                     1   
120110922505                     0                     1   
120110921645                     0                     1   
120110919484                     0                     0   
120110919499                     0                     1   

              first_payment_src_MB  first_payment_src_MC  \
record_id                                                  
120110921391                     0                     0   
120110922505                     0                     0   
120110921645                     0                     0   
120110919484                     0                     0   
120110919499                     0                     0   

              first_payment_src_OF  first_payment_src_VA  \
record_id                                                  
120110921391                     0                     0   
120110922505                     0                     0   
120110921645                     0                     0   
120110919484                     0                     0   
120110919499                     0                     0   

              first_payment_src_WC  first_payment_src_ZZ  pat_age  hiv_drug  
record_id                                                                    
120110921391                     0                     0       20         0  
120110922505                     0                     0       11         0  
120110921645                     0                     0       17         0  
120110919484                     0                     0       19         0  
120110919499                     0                     0       16         0  

[5 rows x 45 columns]

In [15]:
X_demographic.columns

Index(['sex_code_F', 'sex_code_M', 'sex_code_U', 'race_1', 'race_2', 'race_3',
       'race_4', 'race_5', 'race_`', 'ethnicity_1', 'ethnicity_2',
       'ethnicity_`', 'public_health_region_01', 'public_health_region_02',
       'public_health_region_03', 'public_health_region_04',
       'public_health_region_05', 'public_health_region_06',
       'public_health_region_07', 'public_health_region_08',
       'public_health_region_09', 'public_health_region_10',
       'public_health_region_11', 'first_payment_src_09',
       'first_payment_src_11', 'first_payment_src_12', 'first_payment_src_13',
       'first_payment_src_14', 'first_payment_src_15', 'first_payment_src_16',
       'first_payment_src_AM', 'first_payment_src_BL', 'first_payment_src_CH',
       'first_payment_src_CI', 'first_payment_src_HM', 'first_payment_src_LM',
       'first_payment_src_MA', 'first_payment_src_MB', 'first_payment_src_MC',
       'first_payment_src_OF', 'first_payment_src_VA', 'first_payment_src_WC',
  

In [19]:
target = 'pat_status'

index = 'record_id'

personal_demographic_predictors = ['pat_age', 'sex_code', 'race', 'ethnicity', 'public_health_region', 'first_payment_src']
hospital_stay_predictors = ['provider_name', 'type_of_admission', 'source_of_admission', 'admit_weekday', 'length_of_stay']

diag_codes_predictors = ['admitting_diagnosis']
diag_codes_predictors.extend([col for col in X_orig.columns if 'diag_code' in col])

e_code_predictors = [col for col in X_orig.columns if 'e_code' in col]

proc_code_predictors = ['princ_surg_proc_code', 'princ_surg_proc_day', 'princ_icd9_code']
proc_code_predictors.extend([col for col in X_orig.columns if 'oth_surg' in col or 'oth_icd9' in col])

In [20]:
personal_demographic_predictors

['pat_age',
 'sex_code',
 'race',
 'ethnicity',
 'public_health_region',
 'first_payment_src']

In [21]:
X_hospital.columns

Index(['type_of_admission_1', 'type_of_admission_2', 'type_of_admission_3',
       'type_of_admission_4', 'type_of_admission_5', 'type_of_admission_9',
       'source_of_admission_1', 'source_of_admission_2',
       'source_of_admission_4', 'source_of_admission_5',
       'source_of_admission_6', 'source_of_admission_7',
       'source_of_admission_8', 'source_of_admission_9',
       'source_of_admission_A', 'source_of_admission_D',
       'source_of_admission_`', 'admit_weekday', 'length_of_stay',
       'hospital_teaching', 'hospital_CAH', 'hospital_community'],
      dtype='object')

In [23]:
hospital_stay_predictors = ['type_of_admission', 'source_of_admission', 'admit_weekday', 'length_of_stay', 'hospital']

In [24]:
hospital_stay_predictors

['type_of_admission',
 'source_of_admission',
 'admit_weekday',
 'length_of_stay',
 'hospital']

Okay, so let's start off with figuring out what the mode is for each of the demographic and hospital stay predictors, and use that to initialize a default vector for the input.

In [35]:
X_demographic['pat_age'].value_counts()

14    1678
17    1477
18    1351
16    1343
15    1328
19    1247
20     890
13     806
12     505
21     503
9      450
11     296
10     221
8      153
7      119
1       87
2       78
6       44
4       39
5       39
3       34
0       16
Name: pat_age, dtype: int64

In [51]:
prediction_defaults = {
    'sex_code': 'sex_code_M',
    'race': 'race_4',
    'ethnicity': 'ethnicity_2',
    'public_health_region': 'public_health_region_06',
    'first_payment_src': 'first_payment_src_MA',
    'pat_age': 14,
    'hiv_drug': 0,
    'type_of_admission': 'type_of_admission_1',
    'source_of_admission': 'source_of_admission_1',
    'admit_weekday': 1,
    'length_of_stay': 1,
    'hospital': 'hospital_community'
}

In [48]:
X_hospital.sum()

type_of_admission_1        8827
type_of_admission_2        1991
type_of_admission_3        1737
type_of_admission_4           5
type_of_admission_5          90
type_of_admission_9          54
source_of_admission_1      9852
source_of_admission_2       954
source_of_admission_4      1252
source_of_admission_5       240
source_of_admission_6       230
source_of_admission_7        47
source_of_admission_8         5
source_of_admission_9        55
source_of_admission_A         1
source_of_admission_D        57
source_of_admission_`        11
admit_weekday              9706
length_of_stay           117007
hospital_teaching          3865
hospital_CAH                232
hospital_community         8607
dtype: int64

In [40]:
# Since these dataframes are essentially all boolean flags, we can actually just sum each column to get the mode
# of each variable.

# sex_code: men
# race: 4
# ethnicity: 2
# public_health_region: 6
# first_payment_source: 6774

X_demographic.sum()

sex_code_F                   5496
sex_code_M                   6082
sex_code_U                      1
race_1                         98
race_2                        182
race_3                       2186
race_4                       7728
race_5                       2447
race_`                          5
ethnicity_1                  2889
ethnicity_2                  9689
ethnicity_`                    79
public_health_region_01       425
public_health_region_02       327
public_health_region_03      3041
public_health_region_04       688
public_health_region_05       644
public_health_region_06      2853
public_health_region_07      1150
public_health_region_08      1287
public_health_region_09       318
public_health_region_10       378
public_health_region_11      1115
first_payment_src_09         1246
first_payment_src_11           97
first_payment_src_12          664
first_payment_src_13           46
first_payment_src_14            7
first_payment_src_15          253
first_payment_

In [64]:
prediction_vector_length = len(X_demographic.columns) + len(X_hospital.columns) + len(X_diagnoses.columns) + len(X_procedures.columns)
prediction_index = X_demographic.columns.append(X_hospital.columns).append(X_diagnoses.columns).append(X_procedures.columns)

In [65]:
default_prediction_vector = pd.Series(np.zeros(prediction_vector_length), index=prediction_index)

In [245]:
with open("pkls/prediction_vector.pkl", "wb") as picklefile:
    pickle.dump(prediction_vector, picklefile)

In [95]:
gbc_model.predict(np.asarray(prediction_vector).reshape(1, -1))

array(['expired'], dtype=object)

In [96]:
gbc_model.predict_proba(np.asarray(prediction_vector).reshape(1, -1))

array([[0.32937835, 0.67062165]])

In [98]:
import requests

In [99]:
dx_query = "https://clinicaltables.nlm.nih.gov/api/icd9cm_dx/v3/search?terms={}"

response = requests.get(dx_query.format('4275'))
val = response.json()
print(val)

[1, ['4275'], None, [['427.5', ' Cardiac arrest']]]


In [157]:
from sklearn.preprocessing import StandardScaler
ssX = StandardScaler()

In [160]:
scaled_los = ssX.fit_transform(np.asarray(X_orig['length_of_stay']).reshape(-1, 1))

/Users/joycelee/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [162]:
ssX.inverse_transform(scaled_los)

array([[ 4.],
       [ 6.],
       [ 4.],
       ...,
       [ 6.],
       [17.],
       [31.]])

In [163]:
scaled_los

array([[-0.36243684],
       [-0.22331226],
       [-0.36243684],
       ...,
       [-0.22331226],
       [ 0.54187294],
       [ 1.515745  ]])

In [196]:
ssX.inverse_transform([-0.36243684])[0]

3.9999999401220236

In [203]:
ssX.transform(np.asarray([4.]).reshape(-1,1))[0,0]

-0.36243683583475084

In [171]:
ssX_los = StandardScaler()
ssX_los.fit_transform(np.asarray(X_orig['length_of_stay']).reshape(-1,1))

ssX_age = StandardScaler()
ssX_age.fit_transform(np.asarray(X_orig['pat_age']).reshape(-1,1))

/Users/joycelee/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 1.22676964],
       [-1.16575131],
       [ 0.42926265],
       ...,
       [ 0.69509832],
       [ 0.42926265],
       [-0.36824433]])

In [180]:
with open('scalers_los_age.pkl', 'wb') as picklefile:
    pickle.dump([ssX_los, ssX_age], picklefile)

In [185]:
X_train['length_of_stay'].median()

-0.2885367804674306

In [186]:
X_train['pat_age'].median()

0.1706210101898213

In [204]:
def make_prediction(features):
    # When make_prediction is called, make a copy of our prediction_default_dictionary and then
    # change the values according to what features the user changed.

    feature_dict = prediction_defaults.copy()

    for key, value in features.items():
        if key == 'length_of_stay':
            feature_dict[key] = ssX_los.transform(np.asarray([value]).reshape(-1,1))[0,0]
        elif key == 'pat_age':
            feature_dict[key] == ssX_age.transform(np.asarray([value]).reshape(-1,1))[0,0]
        else:
            feature_dict[key] = value
            
    print(feature_dict)
    
    new_prediction = prediction_vector.copy()

    # Every time make_prediction is called, we go ahead and update prediction_vector so that
    # whatever feature it is that the user changed gets updated in the prediction vector.
    # Otherwise, keep all of the defaults that prediction_vector was initialized with.
    for key, value in feature_dict.items():
        if key == 'pat_age' or key =='hiv_drug' or key == 'admit_weekday' or key == 'length_of_stay':
            new_prediction[key] = value
        else:
             new_prediction[value] = 1

    X = np.asarray(new_prediction).reshape(1,-1)
    print(gbc_model.predict(X))
    print(gbc_model.predict_proba(X))
    prob_survived = gbc_model.predict_proba(X)[0, 0]

    result = {
        'prediction': int(prob_survived > 0.5),
        'prob_survived': prob_survived
    }
    return result

In [214]:
print(X_train['length_of_stay'].head())
print(X_orig.loc['120110304733','length_of_stay'])

record_id
420110761749   -0.564326
220110514002    1.159357
120110304733   -0.564326
120110426880   -0.564326
220110444681    1.021463
Name: length_of_stay, dtype: float64
1


In [227]:
make_prediction({'sex_code': 'sex_code_M', 'length_of_stay': '30'})

{'sex_code': 'sex_code_M', 'race': 'race_4', 'ethnicity': 'ethnicity_2', 'public_health_region': 'public_health_region_06', 'first_payment_src': 'first_payment_src_MA', 'pat_age': 14, 'hiv_drug': 0, 'type_of_admission': 'type_of_admission_1', 'source_of_admission': 'source_of_admission_1', 'admit_weekday': 1, 'length_of_stay': 1.4461827140067915, 'hospital': 'hospital_community'}
['alive']
[[0.51910178 0.48089822]]


/Users/joycelee/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype <U2 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


{'prediction': 1, 'prob_survived': 0.5191017772173423}

In [233]:
make_prediction({'sex_code': 'sex_code_F', 'length_of_stay':'30', 'first_payment_src': 'first_payment_src_MA', 'type_of_admission': 'type_of_admission_3'})

{'sex_code': 'sex_code_F', 'race': 'race_4', 'ethnicity': 'ethnicity_2', 'public_health_region': 'public_health_region_06', 'first_payment_src': 'first_payment_src_MA', 'pat_age': 14, 'hiv_drug': 0, 'type_of_admission': 'type_of_admission_3', 'source_of_admission': 'source_of_admission_1', 'admit_weekday': 1, 'length_of_stay': 1.4461827140067915, 'hospital': 'hospital_community'}
['alive']
[[0.53884956 0.46115044]]


/Users/joycelee/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype <U2 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


{'prediction': 1, 'prob_survived': 0.538849564203067}

In [247]:
with open('pkls/prediction_vector.pkl', 'rb') as picklefile:
    z = pickle.load(picklefile)